[package]
name = "yeter"
version = "0.4.0"
edition = "2021"
description = "KISS incremental computation framework"
license = "GPL-3.0"

[dependencies]
state = "0.5"
yeter-macros = { path = "macros", version = "0.1.0" }

[workspace]
members = ["macros"]
