[package]
name = "yeter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "basic"
path = "examples/basic.rs"

[[bin]]
name = "invalidation"
path = "examples/invalidation.rs"

[dependencies]
